image: docker-registry.oxfordnanolabs.local:5000/ont-base-ofan-dev:14.04
# It might be a good idea to switch to a different base image and so avoid installing packages for each commit. 

stages:
    - test
    - pages

before_script:
    - apt-get update
    - apt-get install -y software-properties-common
    - apt-add-repository universe
    - apt-get update
    - apt-get install -y python-pip make python-biopython python-pysam
    - pip install --upgrade sphinx sphinx-argparse sphinx_rtd_theme pytest pycmd futures packaging
    - pip install -e ./

  
do_testing:
  stage: test
  script:
    - make test
  except:
    - tags
    
pages:
  stage: pages
  script: 
    - make docs
    - mv docs/_build/html public
  artifacts:
    paths:
    - public/
  only:
    - master
  except:
    - tags

